{
 "title": "Default Prio Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Workflow Manager: Intake Tasks Scheduled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(aggregation_id, ingestor, locality) (workflow_manager_intake_tasks_scheduled)"
    }
   ]
  },
  {
   "title": "Workflow Manager: Aggregation Tasks Scheduled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(aggregation_id, ingestor, locality) (workflow_manager_aggregation_tasks_scheduled)"
    }
   ]
  },
  {
   "title": "Intake Task Start Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, service, status) (rate(facilitator_intake_tasks_started[5m]))"
    }
   ]
  },
  {
   "title": "Aggregation Task Start Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (namespace, service, status) (rate(facilitator_aggregate_tasks_started[5m]))"
    }
   ]
  },
  {
   "title": "Intake Task Finish Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (namespace, service, status) (rate(facilitator_intake_tasks_finished[5m]))"
    }
   ]
  },
  {
   "title": "Aggregation Task Finish Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (namespace, service, status) (rate(facilitator_aggregate_tasks_finished[5m]))"
    }
   ]
  },
  {
   "title": "Key Rotator: Keys Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (locality) (key_rotator_keys_written)"
    }
   ]
  },
  {
   "title": "Key Rotator: Manifests Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (locality) (key_rotator_manifests_written)"
    }
   ]
  }
 ]
}