{
 "title": "Resource Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (node) (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))) / (sum by (node) (irate(node_cpu_seconds_total[5m]))) * 100"
    }
   ]
  },
  {
   "title": "Container CPU Usage in Excess of Request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) > sum by (namespace, pod, container) (label_replace(kube_pod_container_resource_requests{resource=\"cpu\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"))"
    }
   ]
  },
  {
   "title": "CPU Usage by Containers Without Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (irate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) unless sum by (namespace, pod, container) (label_replace(kube_pod_container_resource_requests{resource=\"cpu\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"))"
    }
   ]
  },
  {
   "title": "Node Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (node) ((node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)) / node_memory_MemTotal_bytes * 100)"
    }
   ]
  },
  {
   "title": "Container Memory Usage in Excess of Request (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "(sum by (namespace, pod, container) (container_memory_usage_bytes{container!=\"\"}) > sum by (namespace, pod, container) (label_replace(kube_pod_container_resource_requests{resource=\"memory\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"))) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Memory Usage by Containers Without Requests (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "expr": "(sum by (namespace, pod, container) (container_memory_usage_bytes{container!=\"\"}) unless sum by (namespace, pod, container) (label_replace(kube_pod_container_resource_requests{resource=\"memory\"}, \"namespace\", \"$1\", \"exported_namespace\", \"(.*)\"))) / 1024 / 1024"
    }
   ]
  }
 ]
}